version: '3.9'
services:
  api:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
      PORT: 8080
      HOST: 0.0.0.0
    ports:
      - '8080:8080'
  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_BASE: http://api:8080
    ports:
      - '5173:5173'
    depends_on:
      - api
